New Gamemode with cornucopia cards
dehydr8/elevation-of-privilege pull request #116
Opened 2021-07-30 09:36 UTC by JonathanDeul

implemented new gamemode with cornucopia cards. Also the starting suit can now be chaned depending on the gamemode.

Resolves #73

2021-07-30 14:26 UTC, ChristophNiehoff requested changes
Already works pretty well!

In the leader board the abbreviation of the played card is very cryptic. For EoP (i.e. for STRIDE), I'd like to have how it was before. For Cornucopia it is more difficult, as several suits have the same starting letter. I propose using the following abbreviations:
* AuthZ
* Crypt
* Sessn
* AuthN
* Data
* Cornu
I hope there enough space for that.

When entering a threat the player can choose a stride categorie. How is this done for Cornucopia?

2021-07-30 14:26 UTC, ChristophNiehoff commented on src/client/pages/create.js
> +                      <option value={suit} key={`start-suit-option-${suit}`}>{getTypeString((this.state.gamemode === "Cornucopia") ? "C" + suit : "" + suit)}</option>
Maybe add the gameMode as a second parameter to getTypeString? I believe that might be better readable

2021-07-30 14:26 UTC, ChristophNiehoff commented on src/utils/constants.js
> +export const INVALID_CARDS = ['E2', 'T2', 'T3', 'T4'];
Why is the first card E2 and not B2?

2021-07-30 14:26 UTC, ChristophNiehoff commented on src/client/components/dealtcard/dealtcard.js
> +      <div className={`playing-card ${(this.props.gamemode === "Cornucopia") ? "c" : ""}card${this.props.card.toLowerCase()} active card-rounded scaled-big`} />
Very often you are using gameMode === Cornucopia. Could you move this to a dedicated function like isGameModeCornucopia?

2021-07-31 11:05 UTC, ChristophNiehoff requested changes

2021-08-03 10:17 UTC, ChristophNiehoff commented
@JonathanDeul  I really like to modified cards!
One thing: For some of the cards (especially AuthZ) there is a white line on the left. Seems to be some kind of offset. Is this something that can easily be fixed?  If not, then it's not important.
![whiteline](https://user-images.githubusercontent.com/10673021/127999511-b43f0387-ffba-4ff0-914f-979801b31752.jpg)

2021-08-03 10:36 UTC, JonathanDeul commented
> @JonathanDeul I really like the modified cards!
> One thing: For some of the cards (especially AuthZ) there is a white line on the left. Seems to be some kind of offset. Is this something that can easily be fixed? If not, then it's not important.
> ![whiteline](https://user-images.githubusercontent.com/10673021/127999511-b43f0387-ffba-4ff0-914f-979801b31752.jpg)

yep. I will fix that!

2021-08-03 10:57 UTC, ChristophNiehoff requested changes

2021-08-03 10:57 UTC, ChristophNiehoff commented on src/client/components/sidebar/sidebar.js
> +        <DealtCard card={dealtCard} gameMode={currentGameMode} />
Is there a reason why you cannot directly use `this.props.G.gameMode` at this place?

2021-08-03 10:57 UTC, ChristophNiehoff commented on src/client/components/threatbar/threatbar.js
> +                      <option value={suit}>{getTypeString(suit, this.props.gameMode)}</option>
In react, when a component is added through a loop, one should add a `key`, see [the docs](https://reactjs.org/docs/lists-and-keys.html#keys).

So, you should add a property like 
```js
key={`threat-category-${suit}`}
```

2021-08-03 10:57 UTC, ChristophNiehoff commented on src/client/pages/create.js
> +      startSuit: "E",
Could you use `DEFAULT_START_SUIT` here?

2021-08-03 10:57 UTC, ChristophNiehoff commented on src/client/pages/create.js
> +      gameMode: "Elevation of Privilege",
Introduce a config parameter like `DEFAULT_GAME_MODE`?

2021-08-03 10:57 UTC, ChristophNiehoff commented on src/utils/constants.js
> +export const INVALID_CARDS = ['B2', 'T2', 'T3', 'T4'];
Are these cards also excluded from Cornucopia?Or do we need separate arrays for EoP and Cornucopia?

2021-08-03 10:57 UTC, ChristophNiehoff commented on src/utils/utils.js
> +  return (gameMode === "OWASP Cornucopia");
Maybe it's a good idea to introduce constants like
```js
const GAMEMODE_EOP = "Elevation of Privilege";
const GAMEMODE_CORNUCOPIA = "OWASP Cornucopia";
```
in `constants.js`

Then one could use them consistently throughout the code (i.e. in the dopdowns, in this function etc.), to nt have these magic strings.

2021-08-03 18:29 UTC, ChristophNiehoff requested changes
We still need a license file for the new subfolder. This should probably say that we modified the original cards and should state the original authors. Maybe we also have to include the CC-BY-SA-3.0 license text (depending on what the licedse actually says...)

And we also have to modify the toplevel license file such that it explicitly excludes the new subfolder.

2021-08-03 18:29 UTC, ChristophNiehoff commented on cornucopiaCards/package.json
> +  "license": "CC BY 3.0"
This should be the shareAlike license.  CC-BY-SA-3.0

2021-08-03 18:29 UTC, ChristophNiehoff commented on cornucopiaCards/package.json
> +  "description": "",
We need a proper description and maybe remove the "main"-field, as this file is not present

2021-08-03 18:29 UTC, ChristophNiehoff commented on cornucopiaCards/package.json
> +  "name": "cornucopia-cards",
Maybe even call the package "cornucopia-cards-modified"?

2021-08-03 18:29 UTC, ChristophNiehoff commented on cornucopiaCards/package.json
> +  "author": "",
Author should probably be "TNG Technology Consulting"

2021-08-03 18:29 UTC, ChristophNiehoff commented on src/client/components/deck/deck.js
> +import { render } from 'react-dom';
Do you need this import? Or is it an error?

2021-08-09 12:52 UTC, merged