#80 pass btn color & vanish after clicked
dehydr8/elevation-of-privilege pull request #90
Opened 2021-07-13 15:07 UTC by matthewejones

Changes the pass button colour to make it more obvious and makes it vanish after clicking.
Also reminds you if you're the last one left to pass.

Resolves #80

2021-07-13 19:47 UTC, ChristophNiehoff commented
@JonathanDeul  Is something missing here? I don't see how the last player gets reminded...

2021-07-13 19:50 UTC, ChristophNiehoff commented
Also: Immediately after the game was created and before the first card was played, there is a strange horizontal line/shadow where usually the pass button is...  Could you also remove this?

![Screenshot from 2021-07-13 21-45-39](https://user-images.githubusercontent.com/10673021/125515898-dd36cd39-e1f2-445f-a0b3-f838a6281d5e.png)

2021-07-13 21:06 UTC, JonathanDeul commented
> 
> 
> @JonathanDeul Is something missing here? I don't see how the last player gets reminded...

yeah, changes in sidebar.js were somehow not applied. I will fix this tmrw.

2021-07-14 11:14 UTC, ChristophNiehoff commented
@JonathanDeul You don't have to create a new PR. You can just update the existing one, i.e. add commits to it.
Could you cherry-pick commits a6a1259 and ad7c923 onto this branch `passbutton`? Then we can close PR #92 as duplicate.

2021-07-15 11:55 UTC, ChristophNiehoff requested changes

2021-07-15 11:55 UTC, ChristophNiehoff commented on src/client/components/sidebar/sidebar.js
> +    if (whopassed[0] === "You" && whopassed[1] === undefined) {
I'm not sure I understand what is happening here:  If `You` are the only one who passed, then show the warning that you are last one to pass? Maybe the variable names need a bit of refinement?

2021-07-15 11:55 UTC, ChristophNiehoff commented on src/client/components/sidebar/sidebar.js
> +          <p class={warningtxt}>You are the last one to pass!</p>
I believe that generally it is more readable to write this as 
```js
const isLastToPass = whopassed[0] === "You" && whopassed[1] === undefined;

<p className={(isLastToPass) ? "visible" : "invisible"} > ... </p>
```

2021-07-15 11:55 UTC, ChristophNiehoff commented on src/client/components/sidebar/sidebar.js
> +          <p class={warningtxt}>You are the last one to pass!</p>
Also the property is called `className`, not `class`.

2021-07-15 12:00 UTC, ChristophNiehoff commented
@JonathanDeul  For me, the horizontal line is still present.

Also we now have two different styles for the buttons. That's the appearance (i.e. the rounded corners) as well as the hover effects. I think there should be one consistent style for all buttons.
![Screenshot from 2021-07-15 13-57-19](https://user-images.githubusercontent.com/10673021/125784459-631b0072-6b82-4e79-9f44-b3383dea5126.png)

And this was probably unwanted, but your CSS changes also had an effect on the Proceed button on the create-page:
![Screenshot from 2021-07-15 13-59-43](https://user-images.githubusercontent.com/10673021/125784614-e033eb57-ea1d-4f57-99d6-c551446f2842.png)

2021-07-15 12:34 UTC, JonathanDeul commented
> 
> 
> @JonathanDeul For me, the horizontal line is still present.
> 
> Also we now have two different styles for the buttons. That's the appearance (i.e. the rounded corners) as well as the hover effects. I think there should be one consistent style for all buttons.
> ![Screenshot from 2021-07-15 13-57-19](https://user-images.githubusercontent.com/10673021/125784459-631b0072-6b82-4e79-9f44-b3383dea5126.png)
> 
> And this was probably unwanted, but your CSS changes also had an effect on the Proceed button on the create-page:
> ![Screenshot from 2021-07-15 13-59-43](https://user-images.githubusercontent.com/10673021/125784614-e033eb57-ea1d-4f57-99d6-c551446f2842.png)

Should I change the pass button back to the original appearance or also change the other buttons?

2021-07-15 20:35 UTC, ChristophNiehoff requested changes
I really like this. Together with the checkmarks this is really awesome!

I just added a few coding style comments

2021-07-15 20:35 UTC, ChristophNiehoff commented on src/client/components/sidebar/sidebar.js
> +              PASS
I think we should go back to `Pass` as this is how buttons are written everywhere else

2021-07-15 20:35 UTC, ChristophNiehoff commented on src/client/components/sidebar/sidebar.js
> +          <p className={(isLastToPass) ? "visible" : "invisible"} >You are the last one to pass!</p>
As written in the other PR, it's better to use conditional rendering than making it invisible via CSS.

2021-07-15 20:35 UTC, ChristophNiehoff commented on src/client/components/sidebar/sidebar.js
> +          <p className={(isLastToPass) ? "visible" : "invisible"} >You are the last one to pass!</p>
Could you also move this line a little bit down? It looks to be a bit to high.
![Screenshot from 2021-07-15 22-24-35](https://user-images.githubusercontent.com/10673021/125852960-179e48ef-f937-48ab-b6dc-56e11437d6e7.png)
And maybe use a color that is better readable on a white background?

2021-07-15 20:35 UTC, ChristophNiehoff commented on src/client/components/sidebar/sidebar.js
> +    const isLastToPass = whopassed[0] === "You" && whopassed[1] === undefined;
Would it work to define this as 
```js
const isLastToPass = this.props.G.passed.length === this.props.ctx.numPlayers-1 && !this.props.G.passed.includes(this.props.playerID)
```
?

2021-07-19 13:35 UTC, ChristophNiehoff approved these changes

2021-07-19 13:35 UTC, merged